package Pidgin::Web::Schema;

use strict;
use base qw/DBIx::Class::Schema::Loader/;

__PACKAGE__->loader_options(
    relationships => 1,
    # debug => 1,
);

=head1 NAME

Pidgin::Web::Schema - DBIx::Class::Schema::Loader class

=head1 SYNOPSIS

See L<Pidgin::Web>

=head1 DESCRIPTION

Generated by L<Catalyst::Model::DBIC::Schema> for use in L<Pidgin::Web::Model::PidginDB>

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;

